[package]
name = "neo6-protocols-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
path = "src/lib.rs"
